config/routes.rb
Rails.application.routes.draw do
  # get 'cards/index' 追加実装のカードのところで勝手にできたやつ
  # get 'cards/new'
  # get 'cards/create'
  # get 'cards/destroy'
  resources :cards, only: [:index, :new, :create, :destroy]

  get 'comments/create'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }

  devise_scope :user do
    get 'users/new_address_preset', to: 'users/registrations#new_address_preset'
    post 'users/create_address_preset', to: 'users/registrations#create_address_preset'
  end

  
  root to: "items#index"
  resources :items do
    resources :transactions, only: [:index, :new, :create]
    resources :comments, only: :create
    member do
      get :purchase_confirm
      post :purchase
    end
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  ## 追加
  validates :card_token, :customer_token, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  before_action :authenticate_user!, only: [:index, :new, :create, :destroy]
  before_action :current_user_has_card, only: [:new, :create]
  
  def index
    ## カードが登録されていないならここで終了
    return unless current_user.card.present?

    Payjp.api_key = ENV["PAYJP_SK"] # 環境変数を読み込む
    customer = Payjp::Customer.retrieve(current_user.card.customer_token) # 先程のカード情報を元に、顧客情報を取得
    @card = customer.cards.first
  end

  def new
  end

  def create

    Payjp.api_key = ENV["PAYJP_SK"] # 環境変数を読み込む

    customer = Payjp::Customer.create(
    description: 'test', # テストカードであることを説明
    card: params[:token] # 登録しようとしているカード情報
    )

    card = Card.new( # トークン化されたカード情報を保存する
      card_token: customer.default_card, # カードトークン
      customer_token: customer.id, # 顧客トークン
      user_id: current_user.id # ログインしているユーザー
    )

    if card.save
      redirect_to cards_path
    else
      redirect_to new_card_path
    end

  end

  def destroy
    if current_user.card.destroy
      redirect_to cards_path, notice: "クレジットカードの削除が完了しました"
    else
      redirect_to cards_path, alert: "クレジットカードの削除に失敗しました"
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/index.html.erb
<%= render "shared/header" %>

<div id="card-wrapper">
  <div id="card-detail__user-name">
    <%= current_user.nickname%>さんのクレジットカード
  </div>
  <% if current_user.card.present? %>

  <div class="card-detail__page-title">
    <h2>カード情報<h2>
  </div>

  <div class="card-detail__card-info">
    【カード番号】
    <br>
    <%= "**** **** **** " + @card[:last4] %>
    <%# カード番号の下4桁を取得 %>
    <br>
    【有効期限】
    <br>
    <%= @card[:exp_month] %>
    <%# 有効期限の「月」を取得 %>
    /
    <%= @card[:exp_year] %>
    <%# 有効期限の「年」を取得 %>
  </div>

  <%= link_to "クレジットカードを削除する", card_path(current_user.card), method: :delete, id: "destroy-card-link"%>

  <% else %>
  カードがありません。
  <br>
  <%= link_to "クレジットカードを登録する", new_card_path, id: "new-card-link"%>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/cards/new.html.erb
<%= render "shared/header" %>

<%= form_with url: cards_path, method: :post, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%# カード情報の入力 %>
    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'number', class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'logo_visa.gif', class: 'card-logo'%>
          <%= image_tag 'logo_mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'jcb-logomark-img-01.gif', class: 'card-logo'%>
          <%= image_tag 'amex-logomark-img-04.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <%= f.text_area 'exp_month', class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
          <p>月</p>
          <%= f.text_area 'exp_year', class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
          <p>年</p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field "cvc",class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
      </div>
    </div>
    <%# /カード情報の入力 %>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn" %>
    </div>
    <% end %>

<%= render "shared/footer" %>